# Generated by Django 5.1.7 on 2025-04-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('card_id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('ssn', models.CharField(max_length=11, unique=True)),
                ('bname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'borrower',
            },
        ),
    ]
