# Generated by Django 5.1.7 on 2025-04-05 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.AutoField(db_column='Author_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(db_column='Isbn', max_length=13, primary_key=True, serialize=False)),
                ('isbn10', models.CharField(blank=True, db_column='Isbn10', max_length=10, null=True, unique=True)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('cover', models.CharField(blank=True, db_column='Cover', max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, db_column='Publisher', max_length=255, null=True)),
                ('pages', models.IntegerField(blank=True, db_column='Pages', null=True)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookLoans',
            fields=[
                ('loan_id', models.AutoField(db_column='Loan_id', primary_key=True, serialize=False)),
                ('date_out', models.DateField(db_column='Date_out')),
                ('due_date', models.DateField(db_column='Due_date')),
                ('date_in', models.DateField(blank=True, db_column='Date_in', null=True)),
            ],
            options={
                'db_table': 'book_loans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('card_id', models.CharField(db_column='Card_id', max_length=10, primary_key=True, serialize=False)),
                ('ssn', models.CharField(db_column='Ssn', max_length=20, unique=True)),
                ('bname', models.CharField(db_column='Bname', max_length=100)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True, unique=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=2, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
            ],
            options={
                'db_table': 'borrower',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookAuthors',
            fields=[
                ('author', models.OneToOneField(db_column='Author_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.authors')),
            ],
            options={
                'db_table': 'book_authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('loan', models.OneToOneField(db_column='Loan_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.bookloans')),
                ('fine_amt', models.DecimalField(db_column='Fine_amt', decimal_places=2, max_digits=10)),
                ('paid', models.IntegerField(blank=True, db_column='Paid', null=True)),
            ],
            options={
                'db_table': 'fines',
                'managed': False,
            },
        ),
    ]
